substitutions:
  # Phases of the Voice Assistant
  voice_assist_idle_phase_id: '1'
  voice_assist_waiting_for_command_phase_id: '2'
  voice_assist_listening_for_command_phase_id: '3'
  voice_assist_thinking_phase_id: '4'
  voice_assist_replying_phase_id: '5'
  voice_assist_not_ready_phase_id: '10'
  voice_assist_error_phase_id: '11'

globals:
  - id: voice_assistant_phase
    type: int
    restore_value: no

microphone:
  - platform: satellite1
    id: sat1_mics
    sample_rate: 48000
    i2s_din_pin: GPIO15
    bits_per_sample: 32bit
    channel: stereo
    pdm: false
    adc_type: external
    i2s_audio_id: i2s_shared

micro_wake_word:
  id: mww
  models:
    - model: https://fph-firmware-assets.s3.us-east-1.amazonaws.com/wake-word/hey_jarvis.json
      id: hey_jarvis
    - model: https://fph-firmware-assets.s3.us-east-1.amazonaws.com/wake-word/okay_nabu.json
      id: okay_nabu
    - model: https://fph-firmware-assets.s3.us-east-1.amazonaws.com/wake-word/stop.json
      id: stop
      internal: true
  vad:
  microphone:
    microphone: sat1_mics
    channels: 1
    gain_factor: 6
  stop_after_detection: false
  on_wake_word_detected:
    - if:
        condition:
          switch.is_off: master_mute_switch
        then:
          - if:
              condition:
                switch.is_on: timer_ringing
              then:
                - switch.turn_off: timer_ringing
              else:
                - if:
                    condition:
                      media_player.is_announcing:
                        id: external_media_player
                    then:
                      - media_player.stop:
                          announcement: true
                          id: external_media_player
                    else:
                      - if:
                          condition:
                            switch.is_on: wake_sound
                          then:
                            - script.execute:
                                id: play_sound
                                priority: true
                                sound_file: "wake_word_triggered_sound"
                            - delay: 300ms
                      - wyoming_satellite.start_pipeline:
                          id: wyoming_satellite_id

select:
  - platform: template
    id: mww_sensitivity_select
    name: "Wake word sensitivity"
    optimistic: true
    initial_option: Slightly sensitive
    restore_value: true
    entity_category: config
    options:
      - Slightly sensitive
      - Moderately sensitive
      - Very sensitive
    on_value:
      lambda: |-
        if (x == "Slightly sensitive") {
          id(okay_nabu).set_probability_cutoff(217);
          id(hey_jarvis).set_probability_cutoff(247);
        } else if (x == "Moderately sensitive") {
          id(okay_nabu).set_probability_cutoff(176);
          id(hey_jarvis).set_probability_cutoff(235);
        } else if (x == "Very sensitive") {
          id(okay_nabu).set_probability_cutoff(143);
          id(hey_jarvis).set_probability_cutoff(212);
        }

script:
  - id: activate_stop_word_if_tts_step_is_long
    then:
      - delay: 1s

  - id: activate_stop_word_once
    then:
      - delay: 1s
      - if:
          condition:
            switch.is_off: timer_ringing
          then:
            - micro_wake_word.enable_model: stop
            - wait_until:
                not:
                  media_player.is_announcing:
                    id: external_media_player
            - if:
                condition:
                  switch.is_off: timer_ringing
                then:
                  - micro_wake_word.disable_model: stop
